import csv
import requests
import json
import os
import sys

#This is a group of helper functions to call the Ravelry.com API. 

from secret import Akey, Pkey

s = requests.Session()
s.auth = (Akey, Pkey)

def get_usernames(start, end, filename, headers=True):
	'''This function gets the usernames from the Ravelry API by looping 
	through the user ids, which are sequential. 
	'''
	with open(filename, 'w') as fh:
		csvwriter = csv.writer(fh)
		if headers:
			csvwriter.writerow(['user_id', 'username'])
		for i in range(start, end+1):
			info = s.get('https://api.ravelry.com/people/' + str(i) + '.json')
			#Here it would be cleaner to do a test for the actual status
			#of the request, but this method still gets most of the 
			#usernames.
			try:
				csvwriter.writerow([i, json.loads(info.text)['user']['username']])
			except:
				pass

def slice_users(filename, N1, N2=None):
	'''This function reads the users back from the csv file generated by 
	get_usernames and then returns a slice (specified by N1 and N2) of 
	this file.
	'''
	with open(filename) as fh:
		csvreader = csv.DictReader(fh)
		users = [(int(line['user_id']), line['username']) for line in csvreader]
	return users[N1:N2]

def get_projects(filename, users):
	'''This function gets and saves into filename a list of projects for 
	each user from the Ravelry API. The users in the unput is a list of 
	couples of user_ids and usernames.
	'''
	with open(filename, 'w') as fh:
		csvwriter = csv.writer(fh)
		for user_id, username in users:
			try:
				info = s.get('https://api.ravelry.com/projects/' + username + '/list.json')
				csvwriter.writerow([user_id, username, info.text])
			except:
				print(sys.exc_info()[0])
				print(user_id, username)

def get_queues(filename, users):
	'''This function gets and saves into filename a list of projects 
	queued by each user from the Ravelry API. The users in the input is 
	a list of couples of user_ids and usernames.
	'''
	with open(filename, 'w') as fh:
		csvwriter = csv.writer(fh)
		for user_id, username in users:
			try:
				info = s.get('https://api.ravelry.com/people/' + username + '/queue/list.json')
				csvwriter.writerow([user_id, username, info.text])
			except:
				print(sys.exc_info()[0])
				print(user_id, username)
				
def get_patterns(filename, patterns):
	'''This function gets and saves into filename a list of patterns 
	found on ravelry.com. The patterns in the unput is 
	a list of pattern_ids.
	'''
	with open(filename, 'w') as fh:
		csvwriter = csv.writer(fh)
		for pattern_id in patterns:
			try:
				info = s.get('https://api.ravelry.com/patterns/' + str(pattern_id) + '.json')
				csvwriter.writerow([pattern_id, info.text])
			except:
				print(sys.exc_info()[0])
				print(pattern_id)

if __name__ == "__main__":
	get_usernames(1, 50, 'users.csv')	
	users = slice_users('users.csv', 0, 20)
	get_projects('user_projects.csv', users)
	get_queues('user_queues.csv', users)
	get_patterns('patters.csv', pattern_ids)
	
